import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacroExpansion
import SwiftSyntaxMacros
import SwiftSyntaxMacrosGenericTestSupport
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import SwiftAIMacrosImpl

/// Expansion tests for `@Structured`.
///
/// These complement the behavioural tests in `SwiftAITests`, which compile real annotated types
/// and exercise them. What can only be tested here is the shape of the generated code and, more
/// importantly, the diagnostics: a declaration the macro rejects cannot appear in a target that
/// has to compile.
///
/// XCTest is used rather than swift-testing because `assertMacroExpansion` reports through
/// `XCTFail`.
final class StructuredMacroExpansionTests: XCTestCase {
    /// The conformances declared on `@Structured` are supplied here so the harness passes the
    /// same `protocols` list the compiler does. Without them the extension expansion sees an
    /// empty request and correctly emits nothing, which would make these tests vacuous.
    private let macros: [String: MacroSpec] = [
        "Structured": MacroSpec(
            type: StructuredMacro.self,
            conformances: ["StructuredOutput", "StructuredValue"]
        ),
        "Guidance": MacroSpec(type: GuidanceMacro.self),
    ]

    // MARK: - Structures

    func testExpandsStruct() {
        assertMacroExpansion(
            """
            @Structured("A point.")
            struct Point {
                @Guidance("The horizontal position.", .range(0...100))
                var x: Int
                var label: String?
            }
            """,
            expandedSource: """
            struct Point {
                var x: Int
                var label: String?

                /// The JSON Schema describing this type, generated by `@Structured`.
                static var jsonSchema: JSONSchema {
                    SwiftAI.StructuredSchema.object(
                        description: "A point.",
                        properties: [
                            SwiftAI.StructuredSchema.Property(name: "x", schema: SwiftAI.StructuredSchema.schema(for: (Int).self), description: "The horizontal position.", constraints: [.range(0 ... 100)]),
                            SwiftAI.StructuredSchema.Property(name: "label", schema: SwiftAI.StructuredSchema.schema(for: (String?).self))
                        ]
                    )
                }

                /// Decodes a complete value, generated by `@Structured`.
                ///
                /// - Throws: `TypeValidationError` naming the property that did not match.
                init(structuredJSON json: JSONValue) throws {
                    self.x = try SwiftAI.StructuredDecoding.decode((Int).self, from: json, key: "x")
                    self.label = try SwiftAI.StructuredDecoding.decode((String?).self, from: json, key: "label")
                }

                typealias Partial = PointPartial

                /// Builds a snapshot from JSON that may still be arriving, generated by `@Structured`.
                static func partial(from json: JSONValue) -> PointPartial {
                    PointPartial(
                        x: SwiftAI.StructuredDecoding.partial((Int).self, from: json, key: "x"),
                        label: SwiftAI.StructuredDecoding.partial((String?).self, from: json, key: "label")
                    )
                }
            }

            /// A partially generated ``Point``.
            ///
            /// Every property is optional because the value is still arriving: a property is
            /// `nil` until the model has produced enough JSON to fill it. Snapshots only ever
            /// gain information, so a view bound to one never has to handle a field disappearing.
            struct PointPartial: Sendable {
                /// The horizontal position.
                var x: SwiftAI.PartialOf<Int>?
                var label: SwiftAI.PartialOf<String?>?

                init(
                    x: SwiftAI.PartialOf<Int>? = nil,
                    label: SwiftAI.PartialOf<String?>? = nil
                ) {
                    self.x = x
                    self.label = label
                }
            }

            extension Point: SwiftAI.StructuredOutput, SwiftAI.StructuredValue {
            }
            """,
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testCopiesAccessLevelOntoGeneratedDeclarations() {
        assertMacroExpansion(
            """
            @Structured
            public struct Token {
                public var value: String
            }
            """,
            expandedSource: """
            public struct Token {
                public var value: String

                /// The JSON Schema describing this type, generated by `@Structured`.
                public static var jsonSchema: JSONSchema {
                    SwiftAI.StructuredSchema.object(
                        description: nil,
                        properties: [
                            SwiftAI.StructuredSchema.Property(name: "value", schema: SwiftAI.StructuredSchema.schema(for: (String).self))
                        ]
                    )
                }

                /// Decodes a complete value, generated by `@Structured`.
                ///
                /// - Throws: `TypeValidationError` naming the property that did not match.
                public init(structuredJSON json: JSONValue) throws {
                    self.value = try SwiftAI.StructuredDecoding.decode((String).self, from: json, key: "value")
                }

                public typealias Partial = TokenPartial

                /// Builds a snapshot from JSON that may still be arriving, generated by `@Structured`.
                public static func partial(from json: JSONValue) -> TokenPartial {
                    TokenPartial(
                        value: SwiftAI.StructuredDecoding.partial((String).self, from: json, key: "value")
                    )
                }
            }

            /// A partially generated ``Token``.
            ///
            /// Every property is optional because the value is still arriving: a property is
            /// `nil` until the model has produced enough JSON to fill it. Snapshots only ever
            /// gain information, so a view bound to one never has to handle a field disappearing.
            public struct TokenPartial: Sendable {
                public var value: SwiftAI.PartialOf<String>?

                public init(
                    value: SwiftAI.PartialOf<String>? = nil
                ) {
                    self.value = value
                }
            }

            extension Token: SwiftAI.StructuredOutput, SwiftAI.StructuredValue {
            }
            """,
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    // MARK: - Enumerations

    func testExpandsStringBackedEnumeration() {
        assertMacroExpansion(
            """
            @Structured("How urgent.")
            enum Priority: String {
                case low
                case veryHigh = "very_high"
            }
            """,
            expandedSource: """
            enum Priority: String {
                case low
                case veryHigh = "very_high"

                /// The JSON Schema describing this enumeration, generated by `@Structured`.
                static var jsonSchema: JSONSchema {
                    SwiftAI.StructuredSchema.enumeration(
                        ["low", "very_high"],
                        description: "How urgent."
                    )
                }

                /// Decodes a value, generated by `@Structured`.
                init(structuredJSON json: JSONValue) throws {
                    self = try SwiftAI.StructuredDecoding.decodeRawRepresentable((Self).self, from: json)
                }
            }

            extension Priority: SwiftAI.StructuredValue {
            }
            """,
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testExpandsEnumerationWithoutRawValues() {
        assertMacroExpansion(
            """
            @Structured
            enum Course {
                case starter, dessert
            }
            """,
            expandedSource: """
            enum Course {
                case starter, dessert

                /// The JSON Schema describing this enumeration, generated by `@Structured`.
                static var jsonSchema: JSONSchema {
                    SwiftAI.StructuredSchema.enumeration(
                        ["starter", "dessert"],
                        description: nil
                    )
                }

                /// Decodes a value, generated by `@Structured`.
                init(structuredJSON json: JSONValue) throws {
                    switch json.stringValue {
                        case "starter":
                        self = .starter
                        case "dessert":
                        self = .dessert
                    default:
                        throw SwiftAI.StructuredDecoding.unknownEnumerationValue(
                            json, permitted: ["starter", "dessert"]
                        )
                    }
                }
            }

            extension Course: SwiftAI.StructuredValue {
            }
            """,
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    // MARK: - Diagnostics

    func testRejectsClasses() {
        assertMacroExpansion(
            """
            @Structured
            class Box {
                var value: String = ""
            }
            """,
            expandedSource: """
            class Box {
                var value: String = ""
            }
            """,
            diagnostics: [
                DiagnosticSpec(message: MacroDiagnostic.notAStructOrEnum.message, line: 1, column: 1)
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testRejectsGenericTypes() {
        assertMacroExpansion(
            """
            @Structured
            struct Wrapper<Value> {
                var value: Value
            }
            """,
            expandedSource: """
            struct Wrapper<Value> {
                var value: Value
            }

            extension Wrapper: SwiftAI.StructuredOutput, SwiftAI.StructuredValue {
            }
            """,
            diagnostics: [
                DiagnosticSpec(message: MacroDiagnostic.genericTypeUnsupported.message, line: 2, column: 8)
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testRequiresExplicitTypeAnnotations() {
        assertMacroExpansion(
            """
            @Structured
            struct Guess {
                var value = 42
            }
            """,
            expandedSource: """
            struct Guess {
                var value = 42
            }

            extension Guess: SwiftAI.StructuredOutput, SwiftAI.StructuredValue {
            }
            """,
            diagnostics: [
                DiagnosticSpec(message: MacroDiagnostic.missingTypeAnnotation("value").message, line: 3, column: 9),
                DiagnosticSpec(message: MacroDiagnostic.emptyStructure.message, line: 2, column: 8),
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testRejectsEnumerationsWithAssociatedValues() {
        assertMacroExpansion(
            """
            @Structured
            enum Outcome {
                case success
                case failure(reason: String)
            }
            """,
            expandedSource: """
            enum Outcome {
                case success
                case failure(reason: String)
            }

            extension Outcome: SwiftAI.StructuredValue {
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: MacroDiagnostic.enumerationWithAssociatedValues.message,
                    line: 2,
                    column: 6
                )
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testRejectsNonStringRawValues() {
        assertMacroExpansion(
            """
            @Structured
            enum Level: Int {
                case one = 1
            }
            """,
            expandedSource: """
            enum Level: Int {
                case one = 1
            }

            extension Level: SwiftAI.StructuredValue {
            }
            """,
            diagnostics: [
                DiagnosticSpec(message: MacroDiagnostic.unsupportedRawValueType("Int").message, line: 2, column: 6)
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }

    func testWarnsWhenGuidanceIsMisplaced() {
        assertMacroExpansion(
            """
            struct Holder {
                @Guidance("Not a stored property.")
                func compute() -> Int { 0 }
            }
            """,
            expandedSource: """
            struct Holder {
                func compute() -> Int { 0 }
            }
            """,
            diagnostics: [
                DiagnosticSpec(
                    message: MacroDiagnostic.guidanceOnNonProperty.message,
                    line: 2,
                    column: 5,
                    severity: .warning
                )
            ],
            macroSpecs: macros,
            indentationWidth: .spaces(4)
        )
    }
}
