import SwiftDiagnostics
import SwiftParser
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// Implements `@Structured`.
///
/// The macro plays three roles at once:
///
/// - **member**: adds `jsonSchema`, `init(structuredJSON:)`, `partial(from:)`, and the `Partial`
///   type alias inside the type, where they have access to private stored properties;
/// - **extension**: adds the `StructuredOutput` or `StructuredValue` conformance;
/// - **peer**: adds the `…Partial` snapshot structure beside the type.
///
/// Generated code never interprets a property's declared type. It writes the type verbatim into
/// `StructuredSchema.schema(for: (T).self)` and `PartialOf<T>`, leaving the compiler to work out
/// what those mean. That is what lets arbitrary nesting — arrays of dictionaries of other
/// `@Structured` types — work without the macro understanding any of it.
public struct StructuredMacro {}

// MARK: - Member expansion

extension StructuredMacro: MemberMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        let description = descriptionArgument(of: node)

        if let structDecl = declaration.as(StructDeclSyntax.self) {
            guard structDecl.genericParameterClause == nil else {
                context.diagnose(Diagnostic(node: structDecl.name, message: MacroDiagnostic.genericTypeUnsupported))
                return []
            }
            return try structMembers(
                typeName: structDecl.name.text,
                declaration: structDecl,
                description: description,
                context: context
            )
        }

        if let enumDecl = declaration.as(EnumDeclSyntax.self) {
            guard enumDecl.genericParameterClause == nil else {
                context.diagnose(Diagnostic(node: enumDecl.name, message: MacroDiagnostic.genericTypeUnsupported))
                return []
            }
            return try enumerationMembers(declaration: enumDecl, description: description, context: context)
        }

        context.diagnose(Diagnostic(node: node, message: MacroDiagnostic.notAStructOrEnum))
        return []
    }

    // MARK: Structs

    private static func structMembers(
        typeName: String,
        declaration: StructDeclSyntax,
        description: ExprSyntax?,
        context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        let access = DeclarationAnalysis.accessLevel(of: declaration)
        let properties = DeclarationAnalysis.storedProperties(of: declaration) { problem in
            context.diagnose(
                Diagnostic(node: problem.anchor, message: MacroDiagnostic.missingTypeAnnotation(problem.name))
            )
        }

        guard !properties.isEmpty else {
            context.diagnose(Diagnostic(node: declaration.name, message: MacroDiagnostic.emptyStructure))
            return []
        }

        let partialTypeName = "\(typeName)Partial"

        let schemaEntries = properties.map { property in
            var arguments = [
                "name: \"\(property.name)\"",
                "schema: SwiftAI.StructuredSchema.schema(for: (\(property.type)).self)",
            ]
            if let description = property.description {
                arguments.append("description: \(description)")
            }
            if !property.constraints.isEmpty {
                let constraints = property.constraints.map(\.description).joined(separator: ", ")
                arguments.append("constraints: [\(constraints)]")
            }
            return "            SwiftAI.StructuredSchema.Property(\(arguments.joined(separator: ", ")))"
        }.joined(separator: ",\n")

        let decodeAssignments = properties.map { property in
            let name = property.name.escapedIdentifier
            let call = "SwiftAI.StructuredDecoding.decode((\(property.type)).self, from: json, key: \"\(property.name)\")"
            return "    self.\(name) = try \(call)"
        }.joined(separator: "\n")

        let partialArguments = properties.map { property in
            let name = property.name.escapedIdentifier
            let call = "SwiftAI.StructuredDecoding.partial((\(property.type)).self, from: json, key: \"\(property.name)\")"
            return "        \(name): \(call)"
        }.joined(separator: ",\n")

        let schema: DeclSyntax = """
            /// The JSON Schema describing this type, generated by `@Structured`.
            \(raw: access)static var jsonSchema: JSONSchema {
                SwiftAI.StructuredSchema.object(
                    description: \(raw: description?.description ?? "nil"),
                    properties: [
            \(raw: schemaEntries)
                    ]
                )
            }
            """

        let initializer: DeclSyntax = """
            /// Decodes a complete value, generated by `@Structured`.
            ///
            /// - Throws: `TypeValidationError` naming the property that did not match.
            \(raw: access)init(structuredJSON json: JSONValue) throws {
            \(raw: decodeAssignments)
            }
            """

        let partialAlias: DeclSyntax = """
            \(raw: access)typealias Partial = \(raw: partialTypeName)
            """

        let partialBuilder: DeclSyntax = """
            /// Builds a snapshot from JSON that may still be arriving, generated by `@Structured`.
            \(raw: access)static func partial(from json: JSONValue) -> \(raw: partialTypeName) {
                \(raw: partialTypeName)(
            \(raw: partialArguments)
                )
            }
            """

        return [schema, initializer, partialAlias, partialBuilder]
    }

    // MARK: Enumerations

    private static func enumerationMembers(
        declaration: EnumDeclSyntax,
        description: ExprSyntax?,
        context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        let access = DeclarationAnalysis.accessLevel(of: declaration)

        if let rawType = DeclarationAnalysis.rawValueType(of: declaration), rawType != "String" {
            context.diagnose(
                Diagnostic(node: declaration.name, message: MacroDiagnostic.unsupportedRawValueType(rawType))
            )
            return []
        }

        guard let cases = DeclarationAnalysis.enumerationCases(of: declaration) else {
            context.diagnose(
                Diagnostic(node: declaration.name, message: MacroDiagnostic.enumerationWithAssociatedValues)
            )
            return []
        }
        guard !cases.isEmpty else {
            context.diagnose(Diagnostic(node: declaration.name, message: MacroDiagnostic.emptyEnumeration))
            return []
        }

        let permittedValues = cases.map { "\"\($0.jsonValue)\"" }.joined(separator: ", ")
        let isStringBacked = DeclarationAnalysis.rawValueType(of: declaration) == "String"

        let schema: DeclSyntax = """
            /// The JSON Schema describing this enumeration, generated by `@Structured`.
            \(raw: access)static var jsonSchema: JSONSchema {
                SwiftAI.StructuredSchema.enumeration(
                    [\(raw: permittedValues)],
                    description: \(raw: description?.description ?? "nil")
                )
            }
            """

        let initializer: DeclSyntax
        if isStringBacked {
            // The raw value initializer already maps every permitted string to a case.
            initializer = """
                /// Decodes a value, generated by `@Structured`.
                \(raw: access)init(structuredJSON json: JSONValue) throws {
                    self = try SwiftAI.StructuredDecoding.decodeRawRepresentable((Self).self, from: json)
                }
                """
        } else {
            let switchCases = cases.map { enumerationCase in
                """
                        case "\(enumerationCase.jsonValue)": self = .\(enumerationCase.name.escapedIdentifier)
                """
            }.joined(separator: "\n")

            initializer = """
                /// Decodes a value, generated by `@Structured`.
                \(raw: access)init(structuredJSON json: JSONValue) throws {
                    switch json.stringValue {
                \(raw: switchCases)
                    default:
                        throw SwiftAI.StructuredDecoding.unknownEnumerationValue(
                            json, permitted: [\(raw: permittedValues)]
                        )
                    }
                }
                """
        }

        return [schema, initializer]
    }

    // MARK: Helpers

    /// The description passed to `@Structured`, if any.
    private static func descriptionArgument(of node: AttributeSyntax) -> ExprSyntax? {
        guard case .argumentList(let arguments)? = node.arguments,
              let first = arguments.first?.expression,
              !first.is(NilLiteralExprSyntax.self)
        else { return nil }
        return first
    }
}

// MARK: - Extension expansion

extension StructuredMacro: ExtensionMacro {
    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        // An enumeration has no meaningful partial snapshot — half of a case name is not a case —
        // so it conforms to the value protocol only, and is generated with
        // `generateObject(model:enumOf:…)` rather than as a top-level object.
        let supported: [String]
        if declaration.is(EnumDeclSyntax.self) {
            supported = ["StructuredValue"]
        } else if declaration.is(StructDeclSyntax.self) {
            supported = ["StructuredOutput", "StructuredValue"]
        } else {
            return []
        }

        // The compiler passes the conformances it still needs covered, and expects every one it
        // asked for to be listed on a generated extension. Emitting a conformance it did not ask
        // for — because the type already declares it by hand — is equally an error, so the
        // intersection is the only correct set to emit.
        let requested = Set(protocols.map(\.trimmedDescription))
        let conformances = supported.filter(requested.contains)
        guard !conformances.isEmpty else { return [] }

        let inheritance = conformances.map { "SwiftAI.\($0)" }.joined(separator: ", ")
        return [try ExtensionDeclSyntax("extension \(type.trimmed): \(raw: inheritance) {}")]
    }
}

// MARK: - Peer expansion

extension StructuredMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        // Only structs get a partial snapshot type.
        guard let structDecl = declaration.as(StructDeclSyntax.self), structDecl.genericParameterClause == nil
        else { return [] }

        let access = DeclarationAnalysis.accessLevel(of: structDecl)
        let typeName = structDecl.name.text
        let properties = DeclarationAnalysis.storedProperties(of: structDecl) { _ in
            // Diagnostics are emitted once, by the member expansion.
        }
        guard !properties.isEmpty else { return [] }

        let storedProperties = properties.map { property in
            let documentation = property.description.map { description in
                "    /// \(literalText(of: description) ?? "The partially generated value.")\n"
            } ?? ""
            return """
                \(documentation)    \(access)var \(property.name.escapedIdentifier): SwiftAI.PartialOf<\(property.type)>?
                """
        }.joined(separator: "\n")

        let initializerParameters = properties.map { property in
            "        \(property.name.escapedIdentifier): SwiftAI.PartialOf<\(property.type)>? = nil"
        }.joined(separator: ",\n")

        let initializerAssignments = properties.map { property in
            "        self.\(property.name.escapedIdentifier) = \(property.name.escapedIdentifier)"
        }.joined(separator: "\n")

        let partial: DeclSyntax = """
            /// A partially generated ``\(raw: typeName)``.
            ///
            /// Every property is optional because the value is still arriving: a property is
            /// `nil` until the model has produced enough JSON to fill it. Snapshots only ever
            /// gain information, so a view bound to one never has to handle a field disappearing.
            \(raw: access)struct \(raw: typeName)Partial: Sendable {
            \(raw: storedProperties)

                \(raw: access)init(
            \(raw: initializerParameters)
                ) {
            \(raw: initializerAssignments)
                }
            }
            """
        return [partial]
    }

    /// The text of a string literal, when it is a plain one, for use in documentation comments.
    private static func literalText(of expression: ExprSyntax) -> String? {
        expression.as(StringLiteralExprSyntax.self)?.representedLiteralValue
    }
}
